[package]
name = "InterfaceAdapters"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
EnterpriseLayer={ path ="../EnterpriseLayer"}
ApplicationLayer={ path ="../ApplicationLayer"}