[package]
name = "ApplicationLayer"
version = "0.1.0"
edition = "2021"

[dependencies]
EnterpriseLayer={ path ="../EnterpriseLayer"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.86"
